//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SEASalon_Project.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public int BranchID { get; set; }
        public string BranchName { get; set; }
        public string BranchLocation { get; set; }
        public string OpeningTime { get; set; }
        public string ClosingTime { get; set; }
    }
}
